// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.3
// source: AsyngRPC/protobuf/ipc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 요청 메시지
type IpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 요청 데이터
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`      // 데이터 크기 (bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcRequest) Reset() {
	*x = IpcRequest{}
	mi := &file_AsyngRPC_protobuf_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcRequest) ProtoMessage() {}

func (x *IpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AsyngRPC_protobuf_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcRequest.ProtoReflect.Descriptor instead.
func (*IpcRequest) Descriptor() ([]byte, []int) {
	return file_AsyngRPC_protobuf_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *IpcRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IpcRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 응답 메시지
type IpcReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // 응답 데이터
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcReply) Reset() {
	*x = IpcReply{}
	mi := &file_AsyngRPC_protobuf_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcReply) ProtoMessage() {}

func (x *IpcReply) ProtoReflect() protoreflect.Message {
	mi := &file_AsyngRPC_protobuf_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcReply.ProtoReflect.Descriptor instead.
func (*IpcReply) Descriptor() ([]byte, []int) {
	return file_AsyngRPC_protobuf_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *IpcReply) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_AsyngRPC_protobuf_ipc_proto protoreflect.FileDescriptor

var file_AsyngRPC_protobuf_ipc_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x41, 0x73, 0x79, 0x6e, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x69, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69,
	0x70, 0x63, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x3a, 0x0a, 0x0a, 0x49, 0x70, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x22, 0x24, 0x0a, 0x08, 0x49, 0x70, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x45, 0x0a, 0x07, 0x49, 0x70, 0x63,
	0x67, 0x72, 0x70, 0x63, 0x12, 0x3a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x2e, 0x69, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x70, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x69, 0x70, 0x63, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x49, 0x70, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a,
	0x61, 0x64, 0x65, 0x6e, 0x37, 0x38, 0x35, 0x36, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x41, 0x73, 0x79, 0x6e, 0x67, 0x52, 0x50, 0x43, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_AsyngRPC_protobuf_ipc_proto_rawDescOnce sync.Once
	file_AsyngRPC_protobuf_ipc_proto_rawDescData []byte
)

func file_AsyngRPC_protobuf_ipc_proto_rawDescGZIP() []byte {
	file_AsyngRPC_protobuf_ipc_proto_rawDescOnce.Do(func() {
		file_AsyngRPC_protobuf_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AsyngRPC_protobuf_ipc_proto_rawDesc), len(file_AsyngRPC_protobuf_ipc_proto_rawDesc)))
	})
	return file_AsyngRPC_protobuf_ipc_proto_rawDescData
}

var file_AsyngRPC_protobuf_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AsyngRPC_protobuf_ipc_proto_goTypes = []any{
	(*IpcRequest)(nil), // 0: ipc_grpc.IpcRequest
	(*IpcReply)(nil),   // 1: ipc_grpc.IpcReply
}
var file_AsyngRPC_protobuf_ipc_proto_depIdxs = []int32{
	0, // 0: ipc_grpc.Ipcgrpc.SendData:input_type -> ipc_grpc.IpcRequest
	1, // 1: ipc_grpc.Ipcgrpc.SendData:output_type -> ipc_grpc.IpcReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AsyngRPC_protobuf_ipc_proto_init() }
func file_AsyngRPC_protobuf_ipc_proto_init() {
	if File_AsyngRPC_protobuf_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AsyngRPC_protobuf_ipc_proto_rawDesc), len(file_AsyngRPC_protobuf_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AsyngRPC_protobuf_ipc_proto_goTypes,
		DependencyIndexes: file_AsyngRPC_protobuf_ipc_proto_depIdxs,
		MessageInfos:      file_AsyngRPC_protobuf_ipc_proto_msgTypes,
	}.Build()
	File_AsyngRPC_protobuf_ipc_proto = out.File
	file_AsyngRPC_protobuf_ipc_proto_goTypes = nil
	file_AsyngRPC_protobuf_ipc_proto_depIdxs = nil
}
